Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 256
      Handler: com.revature.delete_set.DeleteSetHandler
      CodeUri: C:\Users\raney\Desktop\Revature\projects\p3\deleteSet\deleteSet
      Runtime: java8.al2