Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 256
      Handler: com.revature.delete_set.DeleteSetHandler
      CodeUri: C:\Users\Alfonso Holmes\RevatureBank\DeleteSet
      Runtime: java8.al2